### ISSUE TITLE
MilliyetCollectionTREC.rar

### ISSUE THREAD

**Issue by karasahinemre** [BilkentInformationRetrievalGroup/IRCollection#1]
Merhaba,

MilliyetCollectionTREC.rar dosyasını repo üzerinden indirdiğimde 135 bayt görünüyor. Yardımcı olabilir misiniz?

Teşekkürler.

**Comment by fazlican** [comment]
Bu dosyanın boyutu yuksek oldugu için "git lfs" komutuyla indirmeleri gerekiyor.

--------------------------------------------------
FAZLI CAN
Computer Engineering Department
Bilkent University
Ankara, 06800 Turkey
http://www.cs.bilkent.edu.tr/~canf/

**Comment by karasahinemre** [comment]
Lfs ile de denedim. Aşağıdaki hatayı alıyorum ne yazık ki.

"This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access"
